Numpy Practice

In [3]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
zeros_arr = np.zeros((3, 3))  # Creates a 3×3 array filled with zeros
print(zeros_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
rand_arr = np.random.rand(3, 3)
print(rand_arr)

[[0.28765646 0.32276685 0.39888902]
 [0.91582627 0.26737706 0.96436928]
 [0.04706948 0.39318003 0.30120768]]


In [13]:
arr = np.array([1,2,3,4], ndmin=5)
print(arr)

[[[[[1 2 3 4]]]]]


In [10]:
print(arr.reshape((2,2)))  # to change the shape of the array | *NEED* to only provide the shape with matches the number of elements in the array

[[1 2]
 [3 4]]


In [11]:
print(type(arr))  # to check the type of the class for the given object

<class 'numpy.ndarray'>


In [14]:
print(arr.shape)  # to check the shape of the arr | *shape* given info about rows and cols, helpful in matrix algebra

(1, 1, 1, 1, 4)


In [15]:
print(arr.ndim)  # to check the dimensions of the arr

5


In [17]:
arr = np.array([1.1,2.4,3.5,4.6])

print(arr.dtype)  # int32

float64


In [28]:
#i – integer, b – Boolean, u – unsigned integer, f – float, c – complex float, m – timedelta, M – datetime, O – object, S – string, U – unicode string, V – fixed chunk of memory for other type ( void )
arr = np.array(['dogs','cats','horses'], dtype='S')
print(arr.dtype)

|S6


In [38]:

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [39]:
element = arr[0, 1]  # Accessing the element at the first row and second columnslice_ro
w = arr[1, :]  # Slicing the second row

slice_column = arr[:, 2]  # Slicing the third column

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [40]:
w = arr[1, :]  # Slicing the second row

slice_column = arr[:, 2]  # Slicing the third column

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [41]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

In [44]:
# Element-wise arithmetic operations

addition = arr1 + arr2

subtraction = arr1 - arr2

multiplication = arr1 * arr2

division = arr1 / arr2
print(addition)
print(subtraction)
print(multiplication)
print(division)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [45]:
# Statistical operations

mean = np.mean(arr1)

std_dev = np.std(arr2)
print(mean)
print(std_dev)

2.0
0.816496580927726


In [47]:
np.arange(10) + np.arange(10)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])